twilio:
  account_sid: AC0aa94b1bc61266de346803ac86371970
  auth_token:  001f49d85a154022986c08c62f749ae9
  trial_number: +19034209311
  
spring:
  jpa:
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:sms
    driverClassName: org.h2.Driver
    password: password